### ISSUE TITLE
Managing lnksz's contributions

### ISSUE THREAD

**Issue by lnksz** [tum-ens/rivus#34]
Soon I will finish my work on rivus (as far as my thesis goes), and still have a lot of pending PRs, I summarized the properties of them hoping to ease the process/decision of acceptance/merging.
@KSchoenleber 

## Fast ToDo:

- [ ] Add labels like in urbs, so that Issues and PRs can be labelled. This would ease the sorting and handling of those. [[urbs-labels](https://github.com/tum-ens/urbs/labels)]
    - Adding documentation/discussion labels where needed.
    - maintenance, bug, etc...
- [ ] Define version milestones. (Now 0.1, which is the original. Alone #13 should mean a version upgrade.) (See [doc](http://rivus-lnksz.readthedocs.io/en/havasi-playground/index.html#change-log))

## Pull Requests 

As I restructured the project at the beginning, and that was already merged, the PRs mostly consist of self-maintained contributions. However, broader developments can rely on changes now pending in earlier pull-requests.

### Sub Packages
_#self-contained_

- [x] 3D interactive plot #17
- [x] Graph/Network analysis sub package #22
- [x] DB integration #24
- [x] Gridder #28
- [x] Unittests #33

### Core Changes
_#maybe-self-contained_

Merge conflicts can arise, as these operate on the same file. But in different places, so should be ok, or solvable with minimal time investment.

- [x] Line length calc bugfix #13
- [ ] Save function extension #16
- [ ] Excel parsing #23
- [x] Speed-ups #27
- [x] Fix Warnings from Pandas #30
- [x] Ban hubs from vertices #37 

### Broad Changes
_#relying-on-others_

- [x] Runbunch. This is where the threads come together. #32 
    - Relies on: 17, 22, 24, 28, | 13, 16, 23, 27, 30
- [x] Documentation. As changes include docstring and variable name formatting al over the codebase. #40   + main.rivus changes
